name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          ## Criando svg básico
          filename: metrics.plugin.steam.svg
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198255259900"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
          ## Criando svg completo
          name: Profile and detailed game history
          filename2: metrics.plugin.steam.full.svg
          token2: NOT_NEEDED
          base2: ""
          plugin_steam_token2: ${{ secrets.STEAM_TOKEN }}
          plugin_steam2: yes
          plugin_steam_user2: "76561198255259900"

